---
title: "2019 Spokane Crime Report"
author: "Tyler Hart"
date: "January 7, 2020"
output:
  pdf_document:
    fig_caption: yes
    keep_tex: yes
    number_sections: yes
    toc: yes
    toc_depth: 2
  word_document:
    toc: yes
    toc_depth: '2'
  html_document:
    df_print: paged
classoption: landscape
header-includes:
- \usepackage{graphicx}
- \usepackage{float}
- \floatplacement{figure}{H}
---

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(ggthemes)
library(stringr)
library(data.table)
library(scales)
library(lunar)
library(kableExtra)
library(magick)
library(webshot)
library(knitr)
knitr::opts_chunk$set(
  echo = FALSE, 
  message = FALSE,
  warning = FALSE,
  collapse = TRUE,
  results = 'asis',
  fig.align = 'center',
  fig.pos = 'ht',
  dpi = 400,
  fig.path='./figures/2019_Report/',
  dev=c('svg','png'),
  out.width = '100%'
  )

source("./summer_dates.R") # Dates for start / end of summer
source("./text_import.R") # Build crime data frame
source("./categorize_offenses.R") # Categorize offense names

levels(df.crimes$category)[levels(df.crimes$category)=="THEFT OF MOTOR VEHICLE"] <- "VEHICLE THEFT"
```

```{r plot.2019rep_over_time, fig.cap = "Offenses Over Time, September 12, 2017 Onward", echo=FALSE}
df.crimes %>%
  filter(year == 2019) %>%
  group_by(date) %>%
  summarize(offenses = n()) %>%
  ggplot(aes(date, offenses)) + 
  geom_point(size = 3, alpha = 0.5) +
  geom_smooth(method = "auto", color = "blue") +
  geom_smooth(method = "lm", color = "red") +
  geom_vline(xintercept=c(summer_dates$summer_start, summer_dates$summer_end), linetype = 4) +
  geom_vline(xintercept = as.numeric(as.Date(c("2020-01-01","2019-01-01","2018-01-01"))), linetype = 1, size = 1) +
  labs(
    x = "", 
    y = "Offenses", 
    title = "Total Offenses", 
    subtitle = "2019",
    caption = "SOURCE: Spokane Police Department CompStat"
    )
```

```{r plot.2019rep_monthly_comparisons, fig.cap = "Monthly Offenses, 2018-2019", echo=FALSE}
df.crimes %>%
filter(date >= "2018-01-01" & date <= "2019-12-31") %>%
group_by(year, num.month) %>%
summarize(offenses = n()) %>%
ggplot(aes(num.month, offenses, color = year)) +
geom_point(size = 4, alpha = 0.5) +
  ylim(0,1750) +
labs(
  x = "Month",
  y = "Offenses",
  title = "Monthly Offenses",
  subtitle = "2018, 2019",
  color = "Year",
  caption = "SOURCE: Spokane Police Department CompStat"
  ) +
theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

df.crimes %>%
filter(date >= "2018-01-01" & date <= "2019-12-31") %>%
group_by(year, num.month) %>%
summarize(offenses = n()) %>%
ggplot(aes(num.month, offenses, color = year)) +
geom_point(size = 4, alpha = 0.5) +
labs(
  x = "Month",
  y = "Offenses",
  title = "Monthly Offenses",
  subtitle = "2018, 2019",
  color = "Year",
  caption = "SOURCE: Spokane Police Department CompStat"
  ) +
theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

```{r plot.2019rep_weekly_comparisons, fig.cap = "Weekly Offenses, 2018-2019", echo=FALSE}
df.crimes %>%
filter(date >= "2018-01-01" & date <= "2019-12-31") %>%
group_by(year, num.week) %>%
summarize(offenses = n()) %>%
ggplot(aes(num.week, offenses, color = year)) +
geom_point(size = 4, alpha = 0.5) +
ylim(0,400) +
labs(
  x = "Week",
  y = "Offenses",
  title = "Weekly Offenses",
  subtitle = "2018, 2019",
  color = "Year",
  caption = "SOURCE: Spokane Police Department CompStat"
  ) +
theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

df.crimes %>%
filter(date >= "2018-01-01" & date <= "2019-12-31") %>%
group_by(year, num.week) %>%
summarize(offenses = n()) %>%
ggplot(aes(num.week, offenses, color = year)) +
geom_point(size = 4, alpha = 0.5) +
labs(
  x = "Week",
  y = "Offenses",
  title = "Weekly Offenses",
  subtitle = "2018, 2019",
  color = "Year",
  caption = "SOURCE: Spokane Police Department CompStat"
  ) +
theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

```{r plot.2019rep_by_district, fig.cap = "District Offenses, 2019 YTD", echo=FALSE}
df.crimes %>%
  filter(year == 2019) %>%
  count(district) %>%
  ggplot(aes(reorder(district, -n), n, label = n)) +
  geom_col() +
  geom_text(vjust = -0.5) +
  labs(
    x = "Police Districts", 
    title = "Offenses by Police District", 
    subtitle = "2019",
    fill = "Offenses",
    caption = "SOURCE: Spokane Police Department CompStat"
    ) +
  scale_y_continuous("Offenses", labels = comma, expand = c(.1, .1))
```

```{r plot.2019rep_weekly_district_comparisons, fig.cap = "Offenses by Month, District", echo=FALSE}
df.crimes %>%
filter(year == 2019 & !district %in% c("OTH",NA)) %>%
group_by(num.month, district) %>%
summarize(offenses = n()) %>%
ggplot(aes(num.month, offenses, color = district)) +
geom_point(size = 3) +
ylim(0,300) +
labs(
  x = "Month",
  y = "Offenses",
  title = "Monthly Offenses, by District",
  subtitle = "2019",
  color = "District*",
  caption = "
  NOTE: Offenses with no district or 'OTH' omitted
    SOURCE: Spokane Police Department CompStat
  "
  ) +
theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

df.crimes %>%
filter(year == 2019 & !district %in% c("OTH",NA)) %>%
group_by(num.month, district) %>%
summarize(offenses = n()) %>%
ggplot(aes(num.month, offenses, color = district)) +
geom_point(size = 3) +
labs(
  x = "Month",
  y = "Offenses",
  title = "Monthly Offenses, by District",
  subtitle = "2019",
  color = "District*",
  caption = "
  NOTE: Offenses with no district or 'OTH' omitted
    SOURCE: Spokane Police Department CompStat
  "
  ) +
theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```


```{r plot.2019rep_18-19_district_comparison, fig.cap = "District Offenses, 2018-2019", echo=FALSE}
df.crimes %>%
  filter(year %in% c(2018,2019) & !district %in% c("OTH",NA)) %>%
  count(year,district) %>%
  ggplot(aes(reorder(district, -n), n, fill=year, label = n)) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_text(hjust = 1.25, position = position_dodge(width = 1), angle = 90) +
  labs(
  x = "Districts*",
  y = "Offenses",
  title = "Offenses by District",
  subtitle = "2018, 2019",
  fill = "Year",
  caption = "
    NOTE: Offenses with no district or 'OTH' omitted
    SOURCE: Spokane Police Department CompStat
  "
  )
```

```{r plot.2019rep_offenses_by_type, fig.cap = "Types of Offenses, 2019 YTD", echo=FALSE}
df.crimes %>%
  filter(
    year %in% c(2018,2019) & 
    category %in% c("THEFT","BURGLARY","VEHICLE THEFT","ASSAULT","ROBBERY","RAPE")
    ) %>%
  count(category,year) %>%
  ggplot(aes(reorder(category, -n), n, fill=year, label = n)) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_text(vjust = -0.5, position = position_dodge(width = 1)) +
  ylim(0,12750) +
  labs(
  x = "Categories",
  y = "Offenses",
  title = "Common Offense Categories",
  subtitle = "2018, 2019",
  fill = "Year",
  caption = "
    NOTE: Offenses with no district or 'OTH' omitted
    SOURCE: Spokane Police Department CompStat
  "
  ) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```



```{r plot.2019rep_offenses_by_weekday, fig.cap = "Offenses by Day, 2019 YTD", echo=FALSE}
df.crimes %>%
  filter(year == 2019) %>%
  count(dow) %>%
  ggplot(aes(fct_relevel(dow,"Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"), n, label = n)) +
  geom_col() +
  geom_text(vjust = -0.5) +
  labs(
    x = "Days", 
    title = "Offenses by Day", 
    subtitle = "2019",
    caption = "SOURCE: Spokane Police Department CompStat"
    ) +
  scale_y_continuous("Offenses", labels = comma, expand = c(.1, .1))
```