---
title: "WA NIBRS Trends"
author: "Tyler Hart"
date: "4/24/2019"
output: pdf_document
---

```{r setup}
library(readtext)
library(tidyverse)
library(stringi)
library(data.table)
library(doParallel)
library(knitr)
knitr::opts_chunk$set(
  echo = FALSE, 
  message = FALSE,
  fig.pos = 'h',
  fig.align = 'center',
  collapse = TRUE,
  results = 'asis',
  dpi = 400,
  fig.path='./figures/',
  dev=c('pdf', 'png')
  )

# Multi-core
cl <- makePSOCKcluster(4)
registerDoParallel(cl)

source("./data_import.R")

stopCluster(cl)
```

```{r daily_summary}
df.daily_summary <- df.crimes %>%
  filter(incident_date >= "2017-01-01") %>%
  group_by(incident_date) %>%
  summarize(total.daily = n())

df.daily_summary %>% 
  ggplot(aes(incident_date, total.daily)) +
  geom_point() +
  geom_smooth() +
  ggtitle("WA State NIBRS Incidents (2017)") +
  xlab("Date") +
  ylab("Daily Incidents")
```

```{r hourly_summary}
df.hourly_summary <- df.crimes %>%
  filter(!is.na(incident_datetime) & incident_date >= "2017-01-01") %>%
  group_by(incident_hour) %>%
  summarize(total.hour = n())

df.hourly_summary %>% 
  ggplot(aes(incident_hour, total.hour)) +
  geom_col() +
  ggtitle("WA State NIBRS Incident Hours (2017)") +
  xlab("Hour") +
  ylab("Incidents")
```
